k8sServiceHost: kind-control-plane
k8sServicePort: 6443
kubeProxyReplacement: strict
l2announcements:
  enabled: true
  leaseDuration: 3s
  leaseRenewDeadline: 1s
  leaseRetryPeriod: 500ms
devices:
- eth0
- net0
externalIPs:
  enabled:true
operator:
  replicas: 2
